java_binary(
    name = "MavenHelloWorld",
    srcs = ["src/main/java/com/raejz/hello/App.java"],
    main_class = "com.raejz.hello.App",
    deps = [],
)

java_test(
    name = "MavenHelloWorldTest",
    srcs = ["src/test/java/com/raejz/hello/AppTest.java"],
    test_class = "com.raejz.hello.AppTest",
    deps = [],
)
