java_binary(
    name = "JavaHelloWorld",
    srcs = ["src/main/java/com/raejz/greet/HelloWorld.java"],
    main_class = "com.raejz.greet.HelloWorld",
    deps = ["//java-multiplier:IntMultiplierLib"],
)
